-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- USERS TABLE (Syncs with Clerk)
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY, -- Clerk User ID
    email TEXT NOT NULL UNIQUE,
    full_name TEXT,
    stripe_customer_id TEXT,
    role TEXT DEFAULT 'student', -- 'student', 'admin'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- PLANS TABLE (Service offerings)
CREATE TABLE IF NOT EXISTS plans (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL, -- e.g. "Cabin Crew Assessment"
    description TEXT,
    price_cents INTEGER NOT NULL, -- Price in cents (e.g., 2900 for $29.00)
    features JSONB, -- list of features included
    stripe_price_id TEXT, -- For Stripe Checkout
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- SUBSCRIPTIONS/PURCHASES
CREATE TABLE IF NOT EXISTS purchases (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id TEXT REFERENCES users(id),
    plan_id UUID REFERENCES plans(id),
    status TEXT DEFAULT 'active', -- 'active', 'completed', 'cancelled'
    stripe_session_id TEXT,
    purchase_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- SESSIONS (Booked Calls)
CREATE TABLE IF NOT EXISTS sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id TEXT REFERENCES users(id),
    coach_id TEXT, -- Future proofing
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'scheduled', -- 'scheduled', 'completed', 'cancelled'
    meeting_link TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- AI ASSESSMENTS (Bot interactions)
CREATE TABLE IF NOT EXISTS assessments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id TEXT REFERENCES users(id),
    type TEXT NOT NULL, -- 'interview', 'english_test'
    transcript JSONB, -- Full chat history
    ai_feedback TEXT, -- The report generated by the bot
    score INTEGER, -- Optional score 1-100
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Initial Data Seed (Optional)
INSERT INTO plans (name, description, price_cents, features) VALUES 
('Cabin Crew Assessment', 'Full preparation for group exercises and grooming.', 5000, '["Group Exercise Sim", "Grooming Guide", "1hr Video Call"]'),
('Final Interview Prep', 'Master the STAR method and behavioral questions.', 6000, '["Mock Interview", "STAR Method Guide", "Recorded Feedback"]'),
('English Fluency', 'Boost your confidence in speaking English.', 3000, '["30min Convo", "Vocab List", "Accent Correction"]');
